plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

dependencies {
    implementation project(':planner-core')
    implementation 'org.apache.pdfbox:pdfbox:2.0.31'
}

javafx {
    version = '26.0.2'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.swing']
}

application {
    mainClass = 'ee.matteus.pannukas.gui.PancakePlannerApp'
    applicationDefaultJvmArgs = ['--enable-native-access=javafx.graphics']
}
